pointcloud_to_laserscan:
  ros__parameters:
    cloud_in: "/stereo/points"
    scan_out: "/scan"
    angle_min: -1.57
    angle_max: 1.57
    range_min: 0.2
    range_max: 10.0
    use_inf: true
    input_qos_policy: "best_effort"  # Imposta il QoS corretto
